on:
  push:
    branches:
      - main

jobs:
  create_release:
    name: Creating a Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
 
      - name: Install Semantic Release NPM
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release